name: Deploy HTML Page to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code on runner
        uses: actions/checkout@v4

      - name: Run these commands
        run: |
          ls -al
          whoami
          pwd
      - name: Copy files via EC2
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: ./
          target: /home/ubuntu
